### ISSUE TITLE
V2.0: p-Tag zwischen head und body

### ISSUE THREAD

**Issue by rustykowski** [Sioweb/Glossar-Contao-4#12]
Habe gerade auf 2.0.2 aktualisiert. Danke für die neuen Features!

Auf allen Seiten, auf denen das Glossar aktiviert ist, wird nun erst der head geschlossen, dann ein p-Tag geöffnet, dann alle assets eingebunden (css-Links und Scripte) und dann das p-Tag geschlossen.
Beispiel Seite mit aktivem Glossar: https://www.phlebology.de/patienten/behandlung/kompressionstherapie/
ohne Glossar: https://www.phlebology.de/patienten/venenkrankheiten/besenreiser/

**Comment by Sioweb** [comment]
Also erstens: Wow, schöne Seite.

Der Fehler sieht speziell aus, ich schau mir das lokal.

**Comment by rustykowski** [comment]
Ich gebe das Lob an den Designer weiter :-)
