### ISSUE TITLE
V2.0: Position der Overlays wird anders berechnet

### ISSUE THREAD

**Issue by rustykowski** [Sioweb/Glossar-Contao-4#13]
Seit dem Update auf glossar_c4 2.0.2 wird die Größe und Position der Tooltip-Overlays anders berechnet. Steht ein Begriff eher rechts auf der Seite, ragt das Overlay rechts über den Viewport hinaus und kann nur durch horizontales Scrollen erreicht werden. 
Leider bin ich mir nicht mehr ganz sicher, wie Position und Größe vorher berechnet wurden, aber dieses Problem wäre mir sicher aufgefallen.

**Comment by Sioweb** [comment]
Danke dir, das kann sein, ich musste auch am Javascript ein wenig was drehen.

Es ist vermutlich kein Cache oder noch ein überschriebenes Template dass noch angepasst werden muss?

**Comment by rustykowski** [comment]
Nein, ich hatte keines der involvierten Templates modifiziert.
Hast du vielleicht zum Vergleich einen Link zu einer Seite, wo noch das Glossar v 1.x im Einsatz ist?
