### ISSUE TITLE
ce_glossar: Sortierung der Begriffe nicht einstellbar

### ISSUE THREAD

**Issue by rustykowski** [Sioweb/Glossar-Contao-4#16]
In contao 4.7.5 mit Glossar 2.0.9 wirkt sich die Einstellung "Begriffe sortieren" im Inhaltselement Glossar nicht aus. Es wird offenbar immer nach ID sortiert, egal was man einstellt.

**Comment by Sioweb** [comment]
Behoben in 2.0.11
