### ISSUE TITLE
Bilder im TinyMCE werden im Frontend nicht ausgegeben.

### ISSUE THREAD

**Issue by srhinow** [Sioweb/Glossar-Contao-4#19]
genutzte Umgebung: PHP7.2, Contao4.4.40, sioweb/glossar 2.x

Nach viel recherche bin ich darauf gekommen das sobald die Erweiterung "sioweb/glossar": "^2.0" installiert ist werden alle Bilder die im ce_text-Element im TinyMCE-Feld eingefügt wurden nicht im Frontend dargestellt. Das liegt daran das der src-Paramter vom img-Tag kryptisch ist.

`<img src="%7B%7Bfile::589d9814-1e8c-11e6-8fa0-6ea5825a7793%7D%7D" alt="" width="185" height="93">`

Sobald ich diese Erweiterung  "sioweb/glossar": "^2.0" wieder lösche werden die bilder auch wieder angezeigt. Das Modul war in dieser Website auch schon in der alten Contao3-Version im Einsatz wo es das Problem noch nicht gab. Erst nach dem upgrade auf Contao4.4.40 und der Installation von der Version 2 gibt es jetzt diesen Fehler.

**Comment by srhinow** [comment]
Ich habe es jetzt soweit rausgefunden das es im Hook 
`$GLOBALS['TL_HOOKS']['outputFrontendTemplate'][]    = array('Sioweb\Glossar\Polyfill\Contao44\EventListener\Frontend', 'searchGlossarTerms');` auftritt.

Ich würde ja gerne es mit dem ignoreTags versuchen aber dort bekomme ich **den nächsten Fehler**. Denn wenn ich unter Einstellungen (tl_settings) "Glossar aktivieren" anhake rödelt er ewig und eine Subpalette erscheint nicht. Da es ein Error 400 wirft.

**Comment by srhinow** [comment]
Lösungsansatz:
Wenn in der `sioweb/glossar/src/EventListener/Frontend.php` man die Abfrage in Zeile 64 berichtigt zu:
```
        if (false === Config::get('enableGlossar') || $objPage->disableGlossar == 1) {
            return $strContent;
        }
```
dann werden auch die Bilder wieder angezeigt. Denn wenn der Haken ('enableGlossar') nicht gesetzt ist, braucht doch auch der ganze Code in der searchGlossarTerms nicht weiter ausgeführt werden oder?

Die Begrifflichkeit "Glossar aktivieren" ist auch etwas missverständlich, denn auch wenn ich das in den Einstellungen deaktiviere kann ich weiterhin die Glossar-Liste und die Detailansicht sehen. Nur eben das ganze Content-geparse fehlt dann.

**Comment by Sioweb** [comment]
Ho! & Danke für die Info

Die Zeile habe ich eingesetzt in der neuen Version - danke. Ebenfalls sollte die Zeichen { & } nicht mehr in Entities umgewandelt werden.
