### ISSUE TITLE
Englisches Glossar: Link zur ausführlichen Begriffserklärung

### ISSUE THREAD

**Issue by rustykowski** [Sioweb/Glossar-Contao-4#20]
In den Templates glossar_layer und glossar_default wird eine Variable $GLOBALS['glossar']['to_article'] verwendet. Diese steuert einen Linktext wie z.B. "Weiterlesen …".
Die Variable ist aber (zumindest im Englischen) nicht gesetzt, so dass im Frontend ein leerer Link ausgegeben wird.

Natürlich kann jeder diesen String selbst festlegen, z.B. in der langconfig.php:
`if ($GLOBALS['TL_LANGUAGE'] == 'en')
{
    $GLOBALS['glossar']['to_article'] = 'Continue reading';
}`

**Comment by Sioweb** [comment]
Ho! Der Pfad dafür war falsch, danke für den Hinweis!
